instrumentation-security/file-operation/src/main/java/java/io/File_Instrumentation.java, instrumentation-security/jdbc-generic/src/main/java/java/sql/PreparedStatement_Instrumentation.java, instrumentation-security/jdbc-generic/src/main/java/java/sql/Statement_Instrumentation.java, instrumentation-security/low-severity-hooks/build.gradle, instrumentation-security/low-severity-hooks/src/main/java/com/nr/agent/security/random/CryptoUtils.java, instrumentation-security/low-severity-hooks/src/main/java/com/nr/agent/security/random/RandomUtils.java, instrumentation-security/low-severity-hooks/src/main/java/java/security/KeyPairGenerator_Instrumentation.java, instrumentation-security/low-severity-hooks/src/main/java/java/security/MessageDigest_Instrumentation.java, instrumentation-security/low-severity-hooks/src/main/java/java/util/Random_Instrumentation.java, instrumentation-security/low-severity-hooks/src/main/java/javax/crypto/Cipher_Instrumentation.java, instrumentation-security/low-severity-hooks/src/main/java/javax/crypto/KeyGenerator_Instrumentation.java, instrumentation-security/servlet-2.4/src/main/java/javax/servlet/http/HttpServletResponse_Instrumentation.java, instrumentation-security/servlet-2.4/src/main/java/javax/servlet/http/HttpSession_Instrumentation.java, instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/http/HttpServletResponse_Instrumentation.java, instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/http/HttpSession_Instrumentation.java, instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/http/HttpServletResponse_Instrumentation.java, instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/http/HttpSession_Instrumentation.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/Dispatcher.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/utils/AgentUtils.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/JdbcHelper.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/LowSeverityHelper.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ServletHelper.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/AbstractOperation.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/BatchSQLOperation.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/HashCryptoOperation.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/SecureCookieOperation.java, settings.gradle
Added SQL batch operation method instrumentation
Added the following OWASP low-severity hooks
> java.io.File.exists method
> HASH, CRYPTO, RANDOM, SECURECOOKIE and TRUSTBOUNDARY case type
=> OWASP low severity hooks and SQL batch operation hook

build.gradle, gradle.properties, instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/internal/NoOpClassTransformerService.java
APM bumped to 8.0.3
CSEC next version changed to 1.0.2
=> Required version bumps for CSEC and APM post release.

.github/workflows/build-integrated-jar.yml, .github/workflows/publish-to-maven.yml, gradle.properties
As per https://github.com/newrelic/newrelic-java-agent/commit/ddb18397839747175e2b3d0240b858418ad81796 
Change in APM API version
=> Change APM API version to 8.3.0.K2LP

instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/SecurityIntrospector.java, instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/internal/SecurityIntrospectorImpl.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/HttpServletServer.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/HttpServletTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/HttpTestServlet.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/ServletInputStreamTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/ServletOutputStreamTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/ServletRequestTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/ServletResponseTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/ServletTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/instrumentation/security/servlet24/WebServletTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/HttpServletServer.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/HttpServletTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/HttpTestServlet.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/ServletInputStreamTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/ServletOutputStreamTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/ServletRequestTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/ServletResponseTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/ServletTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/instrumentation/security/servlet5/WebServletTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/HttpServletServer.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/HttpServletTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/HttpTestServlet.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/ServletInputStreamTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/ServletOutputStreamTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/ServletRequestTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/ServletResponseTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/ServletTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/instrumentation/security/servlet6/WebServletTest.java
Changes in package names for the servlet unit test cases due to conflict
Fix for the issue of failing a few unit tests
Introspector APIs are updated based on the changes in the instrumentation module
=> [Update] Unit test cases of servlet and issue fixed

instrumentation-security/dynamodb-1.11.390/src/test/java/com/nr/instrumentation/security/dynamodb390/DynamodbTest.java, instrumentation-security/dynamodb-1.11.453/src/test/java/com/nr/instrumentation/security/dynamodb453/DynamodbTest.java, instrumentation-security/dynamodb-1.11.459/src/test/java/com/nr/instrumentation/security/dynamodb459/DynamodbTest.java, instrumentation-security/dynamodb-1.11.80/src/test/java/com/nr/instrumentation/security/dynamodb80/DynamodbTest.java, instrumentation-security/dynamodb-2.1.0/build.gradle, instrumentation-security/dynamodb-2.1.0/src/main/java/com/nr/agent/security/dynamodb_210/DynamoDBUtil.java, instrumentation-security/dynamodb-2.1.0/src/test/java/com/nr/instrumentation/security/dynamodb210/DynamoUtil.java, instrumentation-security/dynamodb-2.1.0/src/test/java/com/nr/instrumentation/security/dynamodb210/DynamodbTest.java, instrumentation-security/dynamodb-2.1.2/build.gradle, instrumentation-security/dynamodb-2.1.2/src/main/java/com/nr/agent/security/dynamodb_212/DynamoDBUtil.java, instrumentation-security/dynamodb-2.1.2/src/test/java/com/nr/instrumentation/security/dynamodb212/DynamoUtil.java, instrumentation-security/dynamodb-2.1.2/src/test/java/com/nr/instrumentation/security/dynamodb212/DynamodbTest.java, instrumentation-security/dynamodb-2.15.34/build.gradle, instrumentation-security/dynamodb-2.15.34/src/main/java/com/nr/agent/security/dynamodb_215/DynamoDBUtil.java, instrumentation-security/dynamodb-2.15.34/src/test/java/com/nr/instrumentation/security/dynamodb215/DynamoUtil.java, instrumentation-security/dynamodb-2.15.34/src/test/java/com/nr/instrumentation/security/dynamodb215/DynamodbTest.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/BatchSQLOperation.java
- updated unit test cases based on the recent instrumentation changes for dynamodb
- minor bug fixes
=> [Update] DynamoDB unit test cases and bug fixes

.github/actions/publish-csec-local/action.yml, .github/actions/publish-csec/action.yml, .github/actions/setup-environment/action.yml, .github/workflows/publish-main-snapshot-to-maven.yml, .github/workflows/publish-release-to-maven.yml, .github/workflows/verify-instrumentation-single.yml, gradle.properties
Fixes in automated GHAs
Reverted APM version to 8.3.0
=> Fixes in automated GHAs

Changelog.md, README.md, gradle.properties, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/IASTDataTransferRequestProcessor.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/logging/IAgentConstants.java
The PR contains version update from 1.0.2 to 1.0.3.
Which contains License Update, Logging improvements and Changelogs
=> 1.0.3 limited-preview

.github/actions/setup-environment/action.yml, .github/workflows/X-Reusable-Build-Security-Agent.yml, .github/workflows/build-integrated-jar.yml, .github/workflows/publish-main-snapshot-to-maven.yml, .github/workflows/publish-release-to-maven.yml, .github/workflows/publish-to-maven.yml
Update default APM repo to k2io and branch to csec-dev
=> Update default repo and branch

.github/workflows/publish-release-to-maven.yml
Changing release version suffix from limited-preview to public-preview
=> Change in release suffix.

Changelog.md, README.md, gradle.properties
Set next version to 1.0.5
Add Supported Vulnerabilities to README.md
=> Version update to 1.0.5

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/CommonUtils.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSReconnectionST.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSUtils.java
Introduced random reconnection delay in WS connection. Now the system waits for  5-15 seconds before reconnecting.
=> Introduced random reconnection delay in WS connection

instrumentation-security/commons-jxpath/build.gradle, instrumentation-security/commons-jxpath/src/main/java/com/nr/instrumentation/security/xpath/commons/jxpath/XPATHUtils.java, instrumentation-security/commons-jxpath/src/main/java/org/apache/commons/jxpath/ri/compiler/JXPathContextReferenceImpl_Instrumentation.java, instrumentation-security/commons-jxpath/src/test/java/JXPathTest.java, instrumentation-security/commons-jxpath/src/test/resources/students.xml, settings.gradle
> - Added instrumentation for commons.jxpath library
> - Added unit test cases for commons.jxpath library
[#NR-118800](https://issues.newrelic.com/browse/NR-118800)
=> [NR-118800] Support for commons.jxpath library

instrumentation-security/servlet-2.4/src/main/java/com/nr/instrumentation/security/servlet24/HttpServletHelper.java, instrumentation-security/servlet-2.4/src/main/java/javax/servlet/ServletContainerInitializer_Instrumentation.java, instrumentation-security/servlet-5.0/src/main/java/com/nr/instrumentation/security/servlet5/HttpServletHelper.java, instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/ServletContainerInitializer_Instrumentation.java, instrumentation-security/servlet-6.0/src/main/java/com/nr/instrumentation/security/servlet6/HttpServletHelper.java, instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/ServletContainerInitializer_Instrumentation.java
Feature for getting url mappings for servlet 2.4, 5.0 and 6.0 
Feature for getting jsp(s)
=> [NEW] URL mappings for servlet modules

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/logging/HealthCheckScheduleThread.java
Removed the Oshi library and added implementation using java.lang.management for getting system stats in SA HC
[#NR-103233](https://issues.newrelic.com/browse/NR-103233)
=> [FIX] SA HC stats empty issue

.github/workflows/X-Reusable-VerifyInstrumentation.yml
Fix in instrumentation module detection for inst verifier. Now taking from settings.gradle.
=> Fix in instrumentation module detection for inst verifier. 

Changelog.md, gradle.properties
=> Version change to 1.0.6

.github/workflows/snyk-vulnerability-scan.yml, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/LowSeverityHelper.java
Add workflow to integrate Snyk Scan, to be triggered on Push to main and scheduled
=> Snyk integration

instrumentation-security/http-async-client-4/src/test/java/com/nr/agent/security/instrumentation/httpasyncclient4/HttpAsyncClient4Test.java, instrumentation-security/httpclient-3/src/test/java/com/nr/agent/security/instrumentation/httpclient3/HttpClientTest.java, instrumentation-security/httpclient-4.0/src/test/java/com/nr/agent/security/instrumentation/httpclient40/HttpClientTest.java, instrumentation-security/httpclient-jdk11/src/test/java/com/nr/agent/security/instrumentation/httpclientJDK11/HttpClientTest.java, instrumentation-security/okhttp-3.0.0/src/test/java/com/nr/agent/security/instrumentation/okhttp30/RealCallTest.java, instrumentation-security/okhttp-3.5.0/src/test/java/com/nr/agent/security/instrumentation/okhttp35/RealCallTest.java, instrumentation-security/okhttp-4.0.0/src/test/java/com/nr/agent/security/instrumentation/okhttp40/ExchangeCodecTest.java, instrumentation-security/urlconnection/src/test/java/com/nr/agent/security/instrumentation/urlconnection/URLConnectionTest.java
Reverts newrelic/csec-java-agent#120
=> Revert "Unit test cases for CSEC parent id header"

instrumentation-security/netty-4.0.0/src/test/java/com/nr/security/instrumentation/netty400/NettyTest.java
Added unit test cases for Netty server
=> Unit test cases for Netty server

instrumentation-security/jcache-1.0.0/src/test/java/com/nr/agent/security/instrumentation/jcache/CustomObject.java, instrumentation-security/jcache-1.0.0/src/test/java/com/nr/agent/security/instrumentation/jcache/JCacheTest.java
Added unit test cases for jcache-1.0.0
=> Unit test cases for JCache

instrumentation-security/lettuce-4.3/build.gradle, instrumentation-security/lettuce-4.3/src/test/java/com/nr/agent/instrumentation/lettuce_4_3/LettuceTest.java, instrumentation-security/lettuce-5.0/build.gradle, instrumentation-security/lettuce-5.0/src/test/java/com/nr/agent/instrumentation/lettuce_5/LettuceTest.java
> Added unit test cases for lettuce-4.3 and lettuce-5 instrumentation modules
=> Unit test cases for lettuce 4.x to 6.x

instrumentation-security/akka-http-core-10.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaHttpCoreTest.scala, instrumentation-security/akka-http-core-10.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaServer.scala, instrumentation-security/akka-http-core-10.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/PlayServer.scala, instrumentation-security/akka-http-core-2.11_10.0.11/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaHttpCoreTest.scala, instrumentation-security/akka-http-core-2.11_10.0.11/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaServer.scala, instrumentation-security/akka-http-core-2.11_10.0.11/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/PlayServer.scala, instrumentation-security/akka-http-core-2.13_10.2.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaHttpCoreTest.scala, instrumentation-security/akka-http-core-2.13_10.2.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/AkkaServer.scala, instrumentation-security/akka-http-core-2.13_10.2.0/src/test/scala/com/nr/agent/security/instrumentation/akka/http/core_10/PlayServer.scala
**TO BE MERGED AFTER**: PR #147 
This PR contains the unit tests for the akka http core support.
=> Unit test for akka http core support

newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
[NR-216080](https://new-relic.atlassian.net/browse/NR-216080)
=> NR-216080: Fix for Null Pointer Exception in stack trace processing

instrumentation-security/akka-http-core-10.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.11_10.0.11/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RequestUtils.java
This PR contains the fix for Akka http core uri path detection issue
=> NR-216061 : Fix for Akka http core uri path detection

instrumentation-security/akka-http-core-10.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.11_10.0.11/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java
NR-216456: Fix for Class Cast Exception and query string extraction from url
=> NR-216456: Fix for Class Cast Exception

newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ServletHelper.java
This contains the fix for the following Jira [NR-216474](https://new-relic.atlassian.net/browse/NR-216474)
=> NR-216474: fix for Null Pointer exception for FILE_OPERATION

newrelic-security-agent/build.gradle, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestClient.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestRequestProcessor.java
Add cc in completed list if fails to fire/generate request or response code is 4xx
=> Add cc in completed list on failure

instrumentation-security/akka-http-core-10.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.11_10.0.11/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaAsyncRequestHandler.scala, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaSyncRequestHandler.scala
This contains the fix for NoSuchElementException in akka-http-core instrumentation
=> Fix for NoSuchElementException in akka-http-core instrumentation

Changelog.md, LICENSE.md, gradle.properties, instrumentation-security/akka-http-core-10.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.11_10.0.11/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/AkkaCoreUtils.java, instrumentation-security/servlet-2.4/src/main/java/javax/servlet/http/HttpServlet_Instrumentation.java, instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/http/HttpServlet_Instrumentation.java, instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/http/HttpServlet_Instrumentation.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/AgentInfo.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/Dispatcher.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/controlcommand/ControlCommandProcessor.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/logging/IAgentConstants.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSUtils.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
Remove cleanup of queue and thread pool on WS reconnect
Fixed user class detection issue
Update license, change log and version
=> Remove cleanup of queue and thread pool on WS reconnect

instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/Server_Instrumentation.java, instrumentation-security/jetty-12/src/main/java/com/newrelic/agent/security/instrumentation/jetty12/server/Server_Instrumentation.java, instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/Server_Instrumentation.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RequestUtils.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestClient.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestRequestProcessor.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/NoOpAgent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/SecurityAgent.java
if failure reason is SSLException or 301, Retry request with different endpoints
=> NR-223852 : Retry request with different endpoint 

Changelog.md, gradle.properties, instrumentation-security/akka-http-core-10.0/src/main/scala/akka/http/scaladsl/Http_Instrumentation.java, instrumentation-security/akka-http-core-2.11_10.0.11/src/main/scala/akka/http/scaladsl/Http_Instrumentation.java, instrumentation-security/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/Http_Instrumentation.java, instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/JettyUtils.java, instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/Server_Instrumentation.java, instrumentation-security/jetty-12/src/main/java/com/newrelic/agent/security/instrumentation/jetty12/server/JettyUtils.java, instrumentation-security/jetty-12/src/main/java/com/newrelic/agent/security/instrumentation/jetty12/server/Server_Instrumentation.java, instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/JettyUtils.java, instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/Server_Instrumentation.java, instrumentation-security/tomcat-7/src/main/java/com/newrelic/agent/security/instrumentation/tomcat7/Connector_Instrumentation.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RequestUtils.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/NoOpAgent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/SecurityAgent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/AppServerInfo.java
Extract Server Configuration for following supported servers
- Tomcat
- Jetty
- Akka HTTP
=> Feature 222151: Extract Server Configuration to resolve IAST localhost connection with application

instrumentation-security/jersey-2.16/build.gradle, instrumentation-security/jersey-2/build.gradle, instrumentation-security/jersey-3/build.gradle
Add test dependencies to jersey modules build.gradle file.
=> Add test dependencies to jersey modules

instrumentation-security/sun-net-httpserver/build.gradle, instrumentation-security/sun-net-httpserver/src/main/java/com/sun/net/httpserver/HttpContext_Instrumentation.java, instrumentation-security/sun-net-httpserver/src/main/java/com/sun/net/httpserver/HttpServerHelper.java, instrumentation-security/sun-net-httpserver/src/main/java/com/sun/net/httpserver/HttpServer_Instrumentation.java, instrumentation-security/sun-net-httpserver/src/test/java/com/nr/agent/security/instrumentation/httpServer/test/HttpServerTest.java, instrumentation-security/sun-net-httpserver/src/test/java/com/nr/agent/security/instrumentation/httpServer/test/Httpserver.java
- API endpoint support for sun-net-httpserver
- unit tests for API endpoint
=> [NR-211181] API-Endpoint support for sun-net-httpserver

instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/ContextHandler_Instrumentation.java, instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/HttpServletHelper.java, instrumentation-security/jetty-11/src/test/java/com/nr/agent/security/instrumentation/jetty11/ServerTest.java, instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/ContextHandler_Instrumentation.java, instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/HttpServletHelper.java, instrumentation-security/jetty-9/src/test/java/com/nr/agent/security/instrumentation/jetty9/ServerTest.java
This PR contains the API endpoint support and unit tests for embed jetty server.
=> [NR-229978] API-Endpoint support for embed jetty server

instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/internal/SecurityIntrospectorImpl.java, instrumentation-security/lettuce-4.3/src/test/java/com/nr/agent/instrumentation/lettuce_4_3/LettuceTest.java, instrumentation-security/lettuce-5.0/src/test/java/com/nr/agent/instrumentation/lettuce_5/LettuceTest.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/SecurityMetaData.java
Added clear function to clean custom attributes in SecurityMetaData.
=> Add clear function to clean custom attribute

instrumentation-security/grpc-1.22.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1220/processor/GrpcRequestProcessor.java, instrumentation-security/grpc-1.4.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc140/processor/GrpcRequestProcessor.java, instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/GrpcRequestProcessor.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestClient.java
gRPC: Added reason in the critical logs fuzz request failed
=> gRPC: Added reason in the critical logs

instrumentation-security/jax-rs-3.0/build.gradle
Exclude milestone release for JAX RS
=> Fix Verifier for JAX RS new release on 29March 4.0.0-M2

instrumentation-security/jax-rs-3.0/build.gradle
Fix Verifier for new release on 29March 4.0.0-M2
=> Exclude milestore release for JAX RS

instrumentation-security/jdbc-sqlserver/build.gradle
Exclude latest released version com.microsoft.sqlserver:mssql-jdbc:12.7.0 released on 08/04/2024
=> Exclude latest released version com.microsoft.sqlserver:mssql-jdbc:12.7.0

instrumentation-security/play-2.13_2.7/src/main/scala/com/newrelic/agent/security/instrumentation/play2_13/GeneratedRouter_Instrumentation.scala, instrumentation-security/play-2.13_2.7/src/main/scala/com/newrelic/agent/security/instrumentation/play2_13/HandlerInvoker.scala, instrumentation-security/play-2.13_2.7/src/test/java/com/nr/agent/security/instrumentation/play2_7/APIEndpointTest.java, instrumentation-security/play-2.4/src/main/scala/com/newrelic/agent/security/instrumentation/play24/GeneratedRouter_Instrumentation.scala, instrumentation-security/play-2.4/src/main/scala/com/newrelic/agent/security/instrumentation/play24/HandlerInvoker.scala, instrumentation-security/play-2.6/src/main/scala/com/newrelic/agent/security/instrumentation/play26/GeneratedRouter_Instrumentation.scala, instrumentation-security/play-2.6/src/main/scala/com/newrelic/agent/security/instrumentation/play26/HandlerInvoker.scala, instrumentation-security/play-2.6/src/test/java/com/nr/agent/security/instrumentation/play26/APIEndpointTest.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/GenericHelper.java
Detection of correct user class for play framework
=> Fix for NR-249053: Detection of correct user class for play framework

newrelic-security-agent/src/main/java/com/newrelic/agent/security/AgentConfig.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/InitLogWriter.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/LogWriter.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/CommonUtils.java
fallback to agent_jar_location as home if newrelic.home is missing
=> Fallback mechanism for NR_CSEC_HOME

instrumentation-security/jdbc-generic/src/main/java/java/sql/PreparedStatement_Instrumentation.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/Dispatcher.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/AgentMetaData.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/SQLOperation.java
Fix for NPE occurring in AgentMetaData and PreparedStatement
=> [NR-262449] Fix for NPE occurring in AgentMetaData and PreparedStatement

.github/workflows/snyk-vulnerability-scan.yml
- updated workflow to use node 20
- pin actions to commit sha's
=> Update Snyk Workflow

instrumentation-security/vertx-web-3.2.0/src/test/java/com/nr/agent/security/instrumentation/vertx/web320/RouteTest.java, instrumentation-security/vertx-web-3.5.1/src/test/java/com/nr/agent/security/instrumentation/vertx/web351/RouteTest.java, instrumentation-security/vertx-web-3.8.3/src/test/java/com/nr/agent/security/instrumentation/vertx/web383/RouteTest.java
Unit Tests to Vertx-Web instrumentation support
=> Unit Tests to Vertx-Web Instrumentation Support

instrumentation-security/servlet-2.4/src/test/java/com/nr/agent/security/instrumentation/servlet24/HttpSessionTest.java, instrumentation-security/servlet-2.4/src/test/java/com/nr/agent/security/instrumentation/servlet24/HttpTestServlet.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/agent/security/instrumentation/servlet5/HttpSessionTest.java, instrumentation-security/servlet-5.0/src/test/java/com/nr/agent/security/instrumentation/servlet5/HttpTestServlet.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/agent/security/instrumentation/servlet6/HttpSessionTest.java, instrumentation-security/servlet-6.0/src/test/java/com/nr/agent/security/instrumentation/servlet6/HttpTestServlet.java
=> [NR-277769] Unit tests for Secure Cookie

instrumentation-security/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/AbstractHandlerMethodMapping_Instrumentation.java, instrumentation-security/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/SpringHelper.java
Detect route of an incoming request for Spring-Webflux framework.
=> [NR-273605] API Endpoint Phase 2 : Detect route of an endpoint for Spring-WebFlux Framework

instrumentation-security/spring-webclient-5.0/build.gradle, instrumentation-security/spring-webclient-5.0/src/test/java/com/nr/agent/security/instrumentation/spring/webclient/SpringWebClientTest.java
Add Unit Tests for Spring-Webclient Instrumentation Support
=> Add Unit Tests for Spring-Webclient Instrumentation Support

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java
Support for proxy settings for connecting to the Security Engine, with known limitation of missing Authentication capabilities.
=> Support for proxy settings for connecting to the SE

newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
If user class is found via annotation use service trace to find user class
=> Locate user class via framework annotation 

newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/URLMappingsHelper.java
Fix for NR-247431, false API Endpoints detected in Servlet Framework
=> [NR-278209] Fix for false API Endpoints detected in Servlet Framework

instrumentation-security/netty-reactor-0.7.0/src/test/java/com/nr/agent/security/instrumentation/netty_reactor/APIEndpointTest.java, instrumentation-security/netty-reactor-0.8.0/src/test/java/com/nr/agent/security/instrumentation/netty_reactor/APIEndpointTest.java
Unit tests for netty reactor API Endpoint Support
=> Unit tests for netty reactor API Endpoint Support

instrumentation-security/spring-webmvc-3.1.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/APIEndpointTest.java, instrumentation-security/spring-webmvc-3.1.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/DummyRequest.java, instrumentation-security/spring-webmvc-5.3.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/APIEndpointTest.java, instrumentation-security/spring-webmvc-5.3.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/DummyRequest.java, instrumentation-security/spring-webmvc-6.0.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/APIEndpointTest.java, instrumentation-security/spring-webmvc-6.0.0/src/test/java/com/nr/agent/security/instrumentation/spring/webmvc/DummyRequest.java
Unit tests for spring route detection
=> Unit tests for spring route detection

gradle/script/java.gradle, instrumentation-security-test/build.gradle, newrelic-security-agent/build.gradle, newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/properties/BuildInfo.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
More details available in: [NR-295033](https://new-relic.atlassian.net/browse/NR-295033)
[NR-295033]: https://new-relic.atlassian.net/browse/NR-295033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NR-295033] Fix for CVEs

newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/URLMappingsHelper.java
Fix for bug NR-250981, where False API reported for CXF framework
=> [NR-288606]: Fix for bug NR-250981, False API reported for CXF framework

instrumentation-security/apache-pekko-http-core-2.13_1/build.gradle, instrumentation-security/apache-pekko-http-core-2.13_1/src/main/scala/org.apache.pekko/http/scaladsl/AsyncRequestHandler.scala, instrumentation-security/apache-pekko-http-core-2.13_1/src/main/scala/org.apache.pekko/http/scaladsl/HttpExt_Instrumentation.java, instrumentation-security/apache-pekko-http-core-2.13_1/src/main/scala/org.apache.pekko/http/scaladsl/PekkoCoreUtils.java, instrumentation-security/apache-pekko-http-core-2.13_1/src/main/scala/org.apache.pekko/http/scaladsl/ResponseFutureHelper.scala, instrumentation-security/apache-pekko-http-core-2.13_1/src/main/scala/org.apache.pekko/http/scaladsl/SyncRequestHandler.scala, instrumentation-security/apache-pekko-http-core-2.13_1/src/test/scala/com/agent/instrumentation/org.apache.pekko/http/core/PekkoHttpCoreTest.scala, instrumentation-security/apache-pekko-http-core-2.13_1/src/test/scala/com/agent/instrumentation/org.apache.pekko/http/core/PekkoServer.scala, instrumentation-security/apache-pekko-http-core-2.13_1/src/test/scala/com/agent/instrumentation/org.apache.pekko/http/core/PlayServer.scala
Unit tests for pekko client and pekko server
=> NR-310454: Unit tests for Apache Pekko

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/RestrictionUtility.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/HttpRequest.java
1. Updated the key generation logic to correctly generate flat maps of header objects.
2. Improved Http Request Parsing Logic
3. XML Parsing Improvement: XXE Attack Prevention
=> NR-319858 : Resolve issue with parsing of header

instrumentation-security/apache-struts2/build.gradle, instrumentation-security/apache-struts2/src/main/java/com/newrelic/agent/security/instrumentation/apache/struts2/StrutsHelper.java, instrumentation-security/apache-struts2/src/main/java/org/apache/struts2/dispatcher/mapper/DefaultActionMapper_Instrumentation.java, instrumentation-security/grails-1.3/src/main/java/com/newrelic/agent/security/instrumentation/grails13/GrailsHelper.java, instrumentation-security/grails-1.3/src/main/java/org/codehaus/groovy/grails/commons/DefaultGrailsController_Instrumentation.java, instrumentation-security/grails-2.0/src/main/java/com/newrelic/agent/security/instrumentation/grails2/GrailsHelper.java, instrumentation-security/grails-2.0/src/main/java/org/codehaus/groovy/grails/commons/DefaultGrailsController_Instrumentation.java, instrumentation-security/grails-3.0/src/main/java/com/newrelic/agent/security/instrumentation/grails3/GrailsHelper.java, instrumentation-security/grails-3.0/src/main/java/org/grails/core/DefaultGrailsController_Instrumentation.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/URLMappingsHelper.java
NR-313390: Route detection support for Apache Struts2 Framework
NR-313392: Route detection support for Grails Framework
=> Route detection Support for Apache Struts2 And Grails Framework

instrumentation-security/dynamodb-1.11.390/src/main/java/com/amazonaws/services/dynamodbv2_1_11_390/AmazonDynamoDBClient_Instrumentation.java, instrumentation-security/dynamodb-1.11.453/src/main/java/com/amazonaws/services/dynamodbv2_1_11_453/AmazonDynamoDBClient_Instrumentation.java, instrumentation-security/dynamodb-1.11.459/src/main/java/com/amazonaws/services/dynamodbv2_1_11_459/AmazonDynamoDBClient_Instrumentation.java, instrumentation-security/dynamodb-1.11.80/src/main/java/com/amazonaws/services/dynamodbv2_1_11_80/AmazonDynamoDBClient_Instrumentation.java, instrumentation-security/dynamodb-2.1.0/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java, instrumentation-security/dynamodb-2.1.0/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java, instrumentation-security/dynamodb-2.1.2/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java, instrumentation-security/dynamodb-2.1.2/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java, instrumentation-security/dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java, instrumentation-security/dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java, instrumentation-security/jedis-1.4.0/src/main/java/redis/clients/jedis/Connection_Instrumentation.java, instrumentation-security/jedis-2.7.1_2.7.2/src/main/java/redis/clients/jedis/Connection_Instrumentation.java, instrumentation-security/jedis-3.0.0/build.gradle, instrumentation-security/jedis-3.0.0/src/main/java/redis/clients/jedis/Connection_Instrumentation.java, instrumentation-security/jedis-4.0.0/src/main/java/redis/clients/jedis/Connection_Instrumentation.java, instrumentation-security/lettuce-4.3/src/main/java/com/lambdaworks/redis/RedisClient_Instrumentation.java, instrumentation-security/lettuce-5.0/build.gradle, instrumentation-security/lettuce-5.0/src/main/java/io/lettuce/core/RedisClient_Instrumentation.java, instrumentation-security/spymemcached-2.12.0/src/main/java/com/newrelic/agent/security/instrumentation/spy/memcached/MemcachedHelper.java, instrumentation-security/spymemcached-2.12.0/src/main/java/net/spy/memcached/MemcachedClient_Instrumentation.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/GenericHelper.java
External connection reporting support for:
- DynamoDB
- Redis client Jedis
- Redis client Lettuce
- Spymemcached
=> [NR-299706] External connection reporting support for DynamoDB, Redis Client, Spymemcached

instrumentation-security/jdbc-generic/src/main/java/java/sql/Driver_Instrumentation.java, instrumentation-security/jdbc-generic/src/main/java/javax/sql/DataSource_Weaved.java, instrumentation-security/jdbc-jtds-generic/src/main/java/net/sourceforge/jtds/jdbc/Driver_Instrumentation.java, instrumentation-security/jdbc-jtds-generic/src/main/java/net/sourceforge/jtds/jdbcx/JtdsDataSource_Instrumentation.java
Report external connections for JDBC, JTDS based Databases
=> [NR-288603] Report external connections for JDBC, JTDS based Databases

instrumentation-security/r2dbc-h2/src/main/java/io/r2dbc/h2/client/SessionClient_Instrumentation.java, instrumentation-security/r2dbc-mariadb/src/main/java/org/mariadb/r2dbc/MariadbConnectionFactory_Instrumentation.java, instrumentation-security/r2dbc-mssql/src/main/java/io/r2dbc/mssql/client/ReactorNettyClient_Instrumentation.java, instrumentation-security/r2dbc-mysql/src/main/java/dev/miku/r2dbc/mysql/client/Client_Instrumentation.java, instrumentation-security/r2dbc-oracle/src/main/java/oracle/r2dbc/impl/OracleConnectionImpl_Instrumentation.java, instrumentation-security/r2dbc-postgresql/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient_Instrumentation.java
ExternalConnection reporting for R2DBC driver
=> [NR-288604] ExternalConnection reporting for R2DBC driver

newrelic-security-agent/src/main/java/com/newrelic/agent/security/AgentConfig.java, newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/IASTDataTransferRequestProcessor.java
Assign default value to next run time if incorrect value to delay/schedule is provided
=> Logging improvement with delay set to incompatible values

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/TransactionUtils.java, newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/GenericHelper.java, newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/SecurityMetaData.java
establish a mechanism to buffer such operations and process them once the HTTP request interception completes, ensuring no valuable events are lost.
=> Pipeline to buffer events with incomplete http request
