newrelic/csec-java-agent

newrelic-security-agent/build.gradle
newrelic-security-api/build.gradle

Fixes build issues due to duplicate resources due to copy instructions and api lib shadowing.

Fix in gradle resource duplication strategy

---

.github/actions/setup-environment-inst-verifier/action.yml
.github/actions/setup-environment/action.yml
.github/workflows/X-Reusable-Build-Security-Agent.yml
.github/workflows/build-integrated-jar.yml
.github/workflows/publish-main-snapshot-to-maven.yml
.github/workflows/publish-release-to-maven.yml
.github/workflows/publish-to-maven.yml

Using main branch for APM instead of k2-integration
Update the proprietary jars to proprietary-jars-20230623.zip

Update to main branch for APM and use new proprietary jars

---

Changelog.md
instrumentation-security/jetty-11/build.gradle

Limiting the version range for Jetty due to the new version release on 7th Aug, 2023

Limiting Jetty Version Range

---

instrumentation-security/java-io-stream/src/main/java/java/io/BufferedReader_Instrumentation.java
instrumentation-security/java-io-stream/src/main/java/java/io/OutputStream_Instrumentation.java
instrumentation-security/java-io-stream/src/main/java/java/io/PrintWriter_Instrumentation.java
instrumentation-security/java-io-stream/src/main/java/java/io/Reader_Instrumentation.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/schedulers/SchedulerHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/IOStreamHelper.java

moved the helper class to api under helpers package 'com.newrelic.api.agent.security.instrumentation.helpers'

Fix ClassNotFoundException for IOStreamHelper

---

instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/SecurityIntrospector.java
instrumentation-security-test/src/main/java/com/newrelic/agent/security/introspec/internal/SecurityIntrospectorImpl.java

Added a new API in instrospector for testing the CSEC parent ID that was added as part of last leg ack

New API in Introspector for unit test cases

---

instrumentation-security/http-async-client-4/src/test/java/com/nr/agent/security/instrumentation/httpasyncclient4/HttpAsyncClient4Test.java
instrumentation-security/httpclient-3/src/test/java/com/nr/agent/security/instrumentation/httpclient3/HttpClientTest.java
instrumentation-security/httpclient-4.0/src/test/java/com/nr/agent/security/instrumentation/httpclient40/HttpClientTest.java
instrumentation-security/httpclient-jdk11/src/test/java/com/nr/agent/security/instrumentation/httpclientJDK11/HttpClientTest.java
instrumentation-security/okhttp-3.0.0/src/test/java/com/nr/agent/security/instrumentation/okhttp30/RealCallTest.java
instrumentation-security/okhttp-3.5.0/src/test/java/com/nr/agent/security/instrumentation/okhttp35/RealCallTest.java
instrumentation-security/okhttp-4.0.0/src/test/java/com/nr/agent/security/instrumentation/okhttp40/ExchangeCodecTest.java
instrumentation-security/urlconnection/src/test/java/com/nr/agent/security/instrumentation/urlconnection/URLConnectionTest.java

Updated unit test cases for the following modules to include test cases for csec parent id header
- http-client-3
- http-client-4
- http-async-client-4
- http-client-jdk11
- okhttp-3
- okhttp-3.5
- okhttp-4
- urlconnection

Unit test cases for CSEC parent id header

---

instrumentation-security/r2dbc-oracle/build.gradle

Updated build.gradle of r2dbc-oracle module to fix the issue of instrumentation verifier was failing

r2dbc-oracle : update build.gradle

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/Dispatcher.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/IASTDataTransferRequestProcessor.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestClient.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestRequestProcessor.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/utils/ApplicationInfoUtils.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/controlcommand/ControlCommandProcessor.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/controlcommand/ControlCommandProcessorThreadPool.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/FileLoggerThreadPool.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/InitLogWriter.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/LogWriter.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/models/javaagent/LogMessage.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/models/javaagent/LogMessageException.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java

NR-163715 Critical error logging via LogMessage event

---

gradle.properties
instrumentation-security/netty-4.0.0/src/main/java/security/io/netty400/channel/ChannelInboundHandler_Instrumentation.java
instrumentation-security/netty-4.0.0/src/main/java/security/io/netty400/channel/ChannelOutboundHandler_Instrumentation.java
instrumentation-security/netty-4.0.0/src/main/java/security/io/netty400/utils/NettyUtils.java
instrumentation-security/netty-4.0.0/src/test/java/com/nr/agent/security/instrumentation/netty400/NettyTest.java

> Added operational lock to hooked method to avoid reading request/response data multiple times
> Updated nr agent version to 8.4.0 as a fix to failing pre-condition in netty server instrumentation (in test env)

[FIX] netty server issues

---

instrumentation-security/file-operation/src/test/java/com/nr/agent/security/instrumentation/javanio/FileSystemProviderTest.java
newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java

ignore .new.class file integrity events which are intentional by UT framework

Fix failure of UT : com.nr.agent.security.instrumentation.javanio.FileSystemProviderTest#testCopy

---

gradle.properties
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/utils/HashGenerator.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/EncryptorUtils.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/NoOpAgent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/SecurityAgent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ServletHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/StringUtils.java

[NR-234888](https://new-relic.atlassian.net/browse/NR-234888) Decryption of IAST replay headers generated from Control Commands.
[NR-234888]: https://new-relic.atlassian.net/browse/NR-234888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NR-234886] IAST replay header decryption

---

newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/NewRelicSecurity.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/FileHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ThreadLocalLockHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/FileIntegrityOperation.java

Create a ThreadLocalLockHelper to ensure only application behaviour is captured

NR-259467 : Fix issue of nested event generation from CSEC's agent itself

---

.github/workflows/X-Reusable-Build-Security-Agent.yml
Changelog.md
README.md
gradle.properties
instrumentation-security/jax-rs-3.0/build.gradle
instrumentation-security/jdbc-sqlserver/build.gradle
newrelic-security-agent/build.gradle
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/NewRelicSecurity.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/FileHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ThreadLocalLockHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/FileIntegrityOperation.java

- [NR-259467](https://new-relic.atlassian.net/browse/NR-259467) Fix issue of nested event generation from CSEC's agent itself [PR-230](https://github.com/newrelic/csec-java-agent/pull/230)
- [NR-256459](https://new-relic.atlassian.net/browse/NR-256459) Exclude JAX RS 4.0.0-M2 version from Instrumentation [PR-231](https://github.com/newrelic/csec-java-agent/pull/231)
- [NR-256461](https://new-relic.atlassian.net/browse/NR-256461) Exclude mssql-jdbc version 12.7.0 from Instrumentation [PR-232](https://github.com/newrelic/csec-java-agent/pull/232)
- [NR-260369](https://new-relic.atlassian.net/browse/NR-260369) Dependency version bump of commons-compress:1.21 to commons-compress:1.26.0 
[NR-259467]: https://new-relic.atlassian.net/browse/NR-259467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

CSEC Java Agent Public Release Version 1.2.1

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RequestUtils.java

Add checks to register media type wrt content-type reflected in CC

Fix for application/form-urlencoded content-type curl with empty body

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/controlcommand/ControlCommandProcessorThreadPool.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java

This should fix issue : missing File Vulnerability as event was not generated by JAVA SA (https://new-relic.atlassian.net/browse/NR-278211)

Flush all control commands on ws client close or open

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/schedulers/FileCleaner.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/FileHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ServletHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/operation/FileIntegrityOperation.java

Implemented a fix by ensuring proper handling of the InvalidPathException wherever the Paths.get method was utilized within the codebase.

Handle InvalidPathException thrown by Paths.get method

---

instrumentation-security/http4s-ember-server-2.13_0.23/build.gradle

Setting the instrumentation module priority to -1 resolved the issue as I see TransactionApiImpl in print statements after making this change. 
https://github.com/newrelic/newrelic-java-agent/issues/1853

Fix for NoOp transactions from Http4s ember server

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/FileLoggerThreadPool.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/InitLogWriter.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/LogFileHelper.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/filelogging/LogWriter.java

the order of precedence and explanation for configuration variables affecting log rotation.
- If `log_daily` is true:
1. A **log_limit_in_kbytes** value greater than zero will result in a composite triggering policy, where logs will roll once per day or when the defined size is reached, retaining up to log_file_count files
2. A **log_limit_in_kbytes** value of zero will result in logs rolling once per day retaining up to log_file_count files
- If `log_daily` is false and **log_limit_in_kbytes** > 0, a sized based policy will be configured, where logs will roll when the defined size is reached, retaining up to log_file_count files
- If `log_daily` is false and **log_limit_in_kbytes** = 0, no log file rolling logic will be configured

Upgrade Log file size and count handling

---

instrumentation-security/vertx-core-3.3.0/build.gradle
instrumentation-security/vertx-core-3.3.0/src/main/java/io/vertx/core/http/HttpServer_Instrumentation.java
instrumentation-security/vertx-core-3.4.0/build.gradle
instrumentation-security/vertx-core-3.4.0/src/main/java/io/vertx/core/http/HttpServer_Instrumentation.java
instrumentation-security/vertx-core-3.7.1/build.gradle
instrumentation-security/vertx-core-3.7.1/src/main/java/io/vertx/core/http/HttpServer_Instrumentation.java
instrumentation-security/vertx-core-4.0.0/build.gradle
instrumentation-security/vertx-core-4.0.0/src/main/java/io/vertx/core/http/HttpServer_Instrumentation.java
instrumentation-security/vertx-web-3.2.0/src/main/java/io/vertx/ext/web/Router_Instrumentation.java
instrumentation-security/vertx-web-3.2.0/src/main/java/io/vertx/ext/web/impl/RouteImpl_Instrumentation.java
instrumentation-security/vertx-web-3.5.1/src/main/java/io/vertx/ext/web/Router_Instrumentation.java
instrumentation-security/vertx-web-3.5.1/src/main/java/io/vertx/ext/web/impl/RouteImpl_Instrumentation.java
instrumentation-security/vertx-web-3.8.3/src/main/java/io/vertx/ext/web/impl/RouteImpl_Instrumentation.java
instrumentation-security/vertx-web-3.8.3/src/main/java/io/vertx/ext/web/impl/RouteState_Instrumentation.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/VertxApiEndpointUtils.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/helper/VertxRoute.java

API Endpoint and Route detection Support for Vert.x Framework

[NR-287771] API Endpoint and Route detection Support for Vert.x Framework

---

instrumentation-security/jersey-2.16/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/HttpRequestHelper.java
instrumentation-security/jersey-2/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/HttpRequestHelper.java
instrumentation-security/jersey-3/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/HttpRequestHelper.java

This is to avoid use of Class.forName method to get class reference, which can lead to ClassNotFoundException

Remove use for class.forName, instead use the class of object itself

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java

Default Auth mechanism requires setting of property jdk.http.auth.tunneling.disabledSchemes

Support Authentication capabilities for Proxy Settings

---

instrumentation-security/apache-tomcat-10/src/main/java/com/newrelic/agent/security/instrumentation/apache/tomcat10/HttpServletHelper.java
instrumentation-security/apache-tomcat-7/src/main/java/com/newrelic/agent/security/instrumentation/apache/tomcat7/HttpServletHelper.java
instrumentation-security/jetty-11/src/main/java/com/newrelic/agent/security/instrumentation/jetty11/HttpServletHelper.java
instrumentation-security/jetty-9/src/main/java/com/newrelic/agent/security/instrumentation/jetty9/HttpServletHelper.java
instrumentation-security/servlet-2.4/src/main/java/com/newrelic/agent/security/instrumentation/servlet24/HttpServletHelper.java
instrumentation-security/servlet-3.0/src/main/java/com/newrelic/agent/security/instrumentation/servlet30/HttpServletHelper.java
instrumentation-security/servlet-5.0/src/main/java/com/newrelic/agent/security/instrumentation/servlet5/HttpServletHelper.java
instrumentation-security/servlet-6.0/src/main/java/com/newrelic/agent/security/instrumentation/servlet6/HttpServletHelper.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/schema/StringUtils.java

Fix for bug [NR-233199](https://new-relic.atlassian.net/browse/NR-233199), where 404 response code is generated when accessing JSP endpoints present in the WEB-INF folder.
[NR-233199]: https://new-relic.atlassian.net/browse/NR-233199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NR-303615]: Fix for API Endpoint reported giving 404 error code

---

newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/utils/AgentUtils.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/schedulers/SchedulerHelper.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/NoOpAgent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/SecurityAgent.java
newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/URLMappingsHelper.java

Report API endpoints immediately after 60 seconds, as soon as new endpoints are discovered

NR-287324: Report API endpoints immediately after 60 seconds

---

.github/actions/build-apm-jar/action.yml

Starting January 30th, 2025 Deprecation notice: v3 of the artifact actions
We will be using V4

using v4 of the artifact actions

---

instrumentation-security/apache-struts2/build.gradle
instrumentation-security/solr-9.0.0/build.gradle

- Limiting instrumentation support in Apache Struts 2, to support the new version 7.0.0 released on Dec 11, 2024.
- Limiting instrumentation support in Apache Solr, to support the new version 9.8.0 released on Jan 21, 2025.

Fix verifier error for Apache Struts 2 and Solr

---

Changelog.md
gradle.properties
instrumentation-security/servlet-2.4/src/main/java/javax/servlet/FilterChain_Instrumentation.java
instrumentation-security/servlet-2.4/src/main/java/javax/servlet/Filter_Instrumentation.java
instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/FilterChain_Instrumentation.java
instrumentation-security/servlet-5.0/src/main/java/jakarta/servlet/Filter_Instrumentation.java
instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/FilterChain_Instrumentation.java
instrumentation-security/servlet-6.0/src/main/java/jakarta/servlet/Filter_Instrumentation.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/Dispatcher.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/dispatcher/DispatcherPool.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestRequestProcessor.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/controlcommand/ControlCommandProcessor.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/models/javaagent/IntCodeControlCommand.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/schedulers/SchedulerHelper.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/IastExclusionUtils.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/RestrictionUtility.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/utils/TTLMap.java
newrelic-security-agent/src/main/java/com/newrelic/agent/security/intcodeagent/websocket/WSClient.java
newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java

- [PR-309](https://github.com/newrelic/csec-java-agent/pull/309) Introduced API Endpoint detection for Resin Server. [NR-293077](https://new-relic.atlassian.net/browse/NR-293077)
- [PR-380](https://github.com/newrelic/csec-java-agent/pull/380) Enabled sending of critical messages upon detection of server ports and confirmation of endpoints.
[NR-368586](https://new-relic.atlassian.net/browse/NR-368586), [NR-368585](https://new-relic.atlassian.net/browse/NR-368585)
- [PR-385](https://github.com/newrelic/csec-java-agent/pull/385) Implemented support for skipping analysis of transitive APIs in IAST maintaining the integrity of the skip list is maintained. [NR-341300](https://new-relic.atlassian.net/browse/NR-341300)
- [PR-374](https://github.com/newrelic/csec-java-agent/pull/374) Resolved an …

Java Security Agent Version 1.6.1

---

instrumentation-security/graphql-java-16.2/build.gradle

Limiting the supported version range for graphql due to new version released on April 7th, 2025.

NR-401021 : Limiting GraphQL Support version range

---

Changelog.md
gradle.properties
instrumentation-security/deserialisation/build.gradle
instrumentation-security/java-reflection/build.gradle
instrumentation-security/jersey-2.16/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/ContainerResponse_Instrumentation.java
instrumentation-security/jersey-2/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/ContainerResponse_Instrumentation.java
instrumentation-security/jersey-3/src/main/java/com/newrelic/agent/security/instrumentation/jersey2/ContainerResponse_Instrumentation.java
instrumentation-security/mule-3.6/src/main/java/org/mule/module/http/internal/domain/response/HttpResponseBuilder_Instrumentation.java
instrumentation-security/mule-3.7/src/main/java/org/mule/module/http/internal/domain/response/HttpResponseBuilder_Instrumentation.java
instrumentation-security/servlet-2.4/src/main/java/javax/servlet/http/HttpServletResponse_Instrumentation.java
instrumentation-security/servlet-2.4/src/test/java/com/nr/agent/security/instrumentation/servlet24/HttpSessionTest.java
newrelic-security-agent/build.gradle
newrelic-security-agent/src/main/java/com/newrelic/agent/security/AgentConfig.java
newrelic-security-api-test-impl/src/main/java/com/newrelic/api/agent/security/Agent.java

- [PR-395](https://github.com/newrelic/csec-java-agent/pull/395) **Support for Deserialization Vulnerability Detection**: Implemented mechanisms to detect vulnerabilities arising from unsafe deserialization processes.
- [PR-395](https://github.com/newrelic/csec-java-agent/pull/395) **Support for Vulnerability Detection of Remote Code Invocation via Reflection**: Enhanced capability to identify security risks associated with remote code execution through reflection.
- [PR-343](https://github.com/newrelic/csec-java-agent/pull/343) **HTTP Response Handling for Vulnerabilities**: Developed the functionality to send HTTP responses for detected vulnerabilities directly to the UI.
- [PR-343](https://github.com/newrelic/csec-java-agent/pull/343) **Trimmed Response Body**: Updated the response …

CSEC Java Agent Version 1.7.0
